import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';

part 'habit.g.dart'; // Will be generated by Hive

@HiveType(typeId: 0)
class Habit {
  @HiveField(0)
  final String id;

  @HiveField(1)
  String title;

  @HiveField(2)
  String description;

  @HiveField(3)
  HabitFrequency frequency;

  @HiveField(4)
  IconData? icon;
  
  @HiveField(5)
  String? category;

  @HiveField(6)
  int streak;

  @HiveField(7)
  DateTime lastCompleted;

  @HiveField(8)
  List<DateTime> completedDates;
  
  @HiveField(9)
  Color? color;

  // Unnamed constructor required by Hive
  Habit(
    this.id,
    this.title,
    this.description,
    this.frequency,
    this.icon,
    this.category,
    this.streak,
    this.lastCompleted,
    this.completedDates,
    this.color,
  );
  
  // Named factory constructor for creating new habits
  factory Habit.create({
    required String title, 
    required String description,
    required HabitFrequency frequency,
    IconData? icon,
    String? category,
    Color? color,
    String? id,
  }) {
    return Habit(
      id ?? const Uuid().v4(),
      title,
      description,
      frequency,
      icon,
      category,
      0,
      DateTime(2000), // Far in past as a default
      [],
      color,
    );
  }
  
  bool isScheduledForToday() {
    final today = DateTime.now();
    final weekday = today.weekday; // 1 = Monday, 7 = Sunday
    
    switch (frequency.type) {
      case FrequencyType.daily:
        return true;
      case FrequencyType.weekly:
        return frequency.daysOfWeek.contains(weekday);
      case FrequencyType.monthly:
        return today.day == frequency.dayOfMonth;
      case FrequencyType.custom:
        switch (frequency.customType) {
          case CustomFrequencyType.everyXDays:
            if (frequency.customDays == 0) return false;
            if (completedDates.isEmpty) return true;
            
            final lastDate = completedDates.last;
            final daysSinceCompletion = today.difference(lastDate).inDays;
            return daysSinceCompletion >= frequency.customDays;
          case CustomFrequencyType.timesPerWeek:
            return completedDates
                    .where((date) =>
                        date.isAfter(today.subtract(Duration(days: today.weekday))) &&
                        date.isBefore(today.add(Duration(days: 7 - today.weekday))))
                    .length <
                frequency.timesPerWeek;
        }
    }
  }

  void markAsCompleted() {
    final today = DateTime.now();
    final todayWithoutTime = DateTime(today.year, today.month, today.day);
    
    // Check if already completed today
    if (completedDates.isNotEmpty) {
      final lastCompleted = completedDates.last;
      final lastCompletedWithoutTime = DateTime(
        lastCompleted.year, lastCompleted.month, lastCompleted.day);
        
      if (lastCompletedWithoutTime.isAtSameMomentAs(todayWithoutTime)) {
        return; // Already completed today
      }
    }

    // Update streak
    if (lastCompleted.year == 2000) {
      // First completion
      streak = 1;
    } else {
      final yesterday = DateTime.now().subtract(Duration(days: 1));
      final yesterdayDate = DateTime(yesterday.year, yesterday.month, yesterday.day);
      final lastCompletedDate = DateTime(
        lastCompleted.year, lastCompleted.month, lastCompleted.day);

      if (yesterdayDate.isAtSameMomentAs(lastCompletedDate) || 
          todayWithoutTime.isAtSameMomentAs(lastCompletedDate)) {
        streak++;
      } else {
        streak = 1; // Reset streak
      }
    }

    lastCompleted = today;
    completedDates.add(today);
  }

  void unmarkCompletion() {
    final today = DateTime.now();
    final todayWithoutTime = DateTime(today.year, today.month, today.day);

    // Remove today's completion if exists
    completedDates.removeWhere((date) {
      final dateWithoutTime = DateTime(date.year, date.month, date.day);
      return dateWithoutTime.isAtSameMomentAs(todayWithoutTime);
    });

    // Recalculate streak and lastCompleted
    if (completedDates.isEmpty) {
      streak = 0;
      lastCompleted = DateTime(2000);
    } else {
      completedDates.sort((a, b) => b.compareTo(a)); // Sort descending
      lastCompleted = completedDates.first;
      
      // Recalculate streak
      int tempStreak = 1;
      for (int i = 0; i < completedDates.length - 1; i++) {
        final currentDate = DateTime(
          completedDates[i].year, 
          completedDates[i].month, 
          completedDates[i].day
        );
        final nextDate = DateTime(
          completedDates[i+1].year, 
          completedDates[i+1].month, 
          completedDates[i+1].day
        );
        
        final difference = currentDate.difference(nextDate).inDays;
        
        if (difference == 1) {
          tempStreak++;
        } else {
          break;
        }
      }
      streak = tempStreak;
    }
  }
}

@HiveType(typeId: 1)
class HabitFrequency {
  @HiveField(0)
  final FrequencyType type;
  
  @HiveField(1)
  final List<int> daysOfWeek; // 1=Monday, 7=Sunday
  
  @HiveField(2)
  final int dayOfMonth; // 1-31
  
  @HiveField(3)
  final int customDays; // Every X days
  
  @HiveField(4)
  final int timesPerWeek; // X times per week
  
  @HiveField(5)
  final CustomFrequencyType customType;

  // Unnamed constructor required by Hive
  HabitFrequency(this.type, this.daysOfWeek, this.dayOfMonth, this.customDays, this.timesPerWeek, this.customType);

  factory HabitFrequency.daily() {
    return HabitFrequency(FrequencyType.daily, [], 0, 0, 0, CustomFrequencyType.everyXDays);
  }

  factory HabitFrequency.weekly({required List<int> days}) {
    return HabitFrequency(FrequencyType.weekly, days, 0, 0, 0, CustomFrequencyType.everyXDays);
  }

  factory HabitFrequency.monthly({required int day}) {
    return HabitFrequency(FrequencyType.monthly, [], day, 0, 0, CustomFrequencyType.everyXDays);
  }

  factory HabitFrequency.custom({required int days}) {
    return HabitFrequency(FrequencyType.custom, [], 0, days, 0, CustomFrequencyType.everyXDays);
  }
  
  factory HabitFrequency.timesPerWeek({required int times}) {
    return HabitFrequency(FrequencyType.custom, [], 0, 0, times, CustomFrequencyType.timesPerWeek);
  }
  
  String getDisplayText() {
    switch (type) {
      case FrequencyType.daily:
        return 'Täglich';
      case FrequencyType.weekly:
        if (daysOfWeek.length == 7) return 'Täglich';
        final dayNames = daysOfWeek.map((day) => _getDayName(day)).join(', ');
        return 'Wöchentlich: $dayNames';
      case FrequencyType.monthly:
        return 'Monatlich: Tag $dayOfMonth';
      case FrequencyType.custom:
        switch (customType) {
          case CustomFrequencyType.everyXDays:
            return 'Alle $customDays Tage';
          case CustomFrequencyType.timesPerWeek:
            return '$timesPerWeek Mal pro Woche';
        }
    }
  }
  
  String _getDayName(int day) {
    switch (day) {
      case 1: return 'Mo';
      case 2: return 'Di';
      case 3: return 'Mi';
      case 4: return 'Do';
      case 5: return 'Fr';
      case 6: return 'Sa';
      case 7: return 'So';
      default: return '';
    }
  }
}

@HiveType(typeId: 2)
enum FrequencyType {
  @HiveField(0)
  daily,
  
  @HiveField(1)
  weekly,
  
  @HiveField(2)
  monthly,
  
  @HiveField(3)
  custom
}

@HiveType(typeId: 5)
enum CustomFrequencyType {
  @HiveField(0)
  everyXDays,
  
  @HiveField(1)
  timesPerWeek
}